### ISSUE TITLE
require libcudnn.so.5. while I have libcudnn.so.7

### ISSUE THREAD

**Issue by apeterswu** [karpathy/neuraltalk2#110]
When I try to evaluate the images, I got the error: libcudnn (R5) not found in library path. so it shows that libcudnn.so.5 required, but I actually have libcudnn.so.7. How to fix with this? thanks.

**Comment by apeterswu** [comment]
I got to know, that because the version of Cudnn is not match with cuda-toolkit. I update cudnn now. it works now.
