### ISSUE TITLE
 Error in CuDNN: CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by ashwinnair14** [karpathy/neuraltalk2#44]
Hi,
I have followed all the steps and installed all dependencies required for neuraltalk2.
while running th eval.lua

DataLoaderRaw loading images from folder: 	/home/anilil/caffe/examples/images/	
listing all images in directory /home/anilil/caffe/examples/images/	
DataLoaderRaw found 3 images	
constructing clones inside the LanguageModel	
/home/anilil/torch/install/bin/luajit: /home/anilil/torch/install/share/lua/5.1/cudnn/init.lua:58: Error in CuDNN: CUDNN_STATUS_NOT_SUPPORTED
stack traceback:
	[C]: in function 'error'
	/home/anilil/torch/install/share/lua/5.1/cudnn/init.lua:58: in function 'errcheck'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:385: in function 'updateOutput'
	/home/anilil/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	eval.lua:121: in function 'eval_split'
	eval.lua:173: in main chunk
	[C]: in function 'dofile'
	...ilil/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

I already tried the https://github.com/karpathy/neuraltalk2/issues/19 and the https://github.com/karpathy/neuraltalk2/issues/20

I already installed the latest version of Cudnn.

**Comment by zdx3578** [comment]
from issue 32 ，from soumith 

if you have cudnn 4.0 then you need the cudnn.torch r4 bindings.
git clone https://github.com/soumith/cudnn.torch -b R4
cd cudnn.torch
luarocks make

use above ， i fix the error

**Comment by gwern** [comment]
zdx: thanks, I had the same issue and that fixed it.
