### ISSUE TITLE
cuda runtime error (2) : out of memory at THCStorage.cu

### ISSUE THREAD

**Issue by aronfothi** [karpathy/neuraltalk2#52]
Hi All,
10 days ago I managed to run the neuraltalk2 eval. Yesterday (29.12) I reinstalled the torch and the dependencies like cutorch. Since that i get the next error message when i try to run eval with the same parameters:
>constructing clones inside the LanguageModel	
/home/aron/torch/install/bin/luajit: /home/aron/torch/install/share/lua/5.1/torch/File.lua:298: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-2709/cutorch/lib/THC/generic/THCStorage.cu:40
stack traceback:
	[C]: in function 'read'
	/home/aron/torch/install/share/lua/5.1/torch/File.lua:298: in function </home/aron/torch/install/share/lua/5.1/torch/File.lua:212>
	[C]: in function 'read'
	/home/aron/torch/install/share/lua/5.1/torch/File.lua:298: in function 'readObject'
	/home/aron/torch/install/share/lua/5.1/torch/File.lua:316: in function 'readObject'
	/home/aron/torch/install/share/lua/5.1/torch/File.lua:300: in function 'readObject'
	/home/aron/torch/install/share/lua/5.1/torch/File.lua:316: in function 'readObject'
	/home/aron/torch/install/share/lua/5.1/torch/File.lua:316: in function 'readObject'
	/home/aron/torch/install/share/lua/5.1/torch/File.lua:316: in function 'readObject'
	/home/aron/torch/install/share/lua/5.1/torch/File.lua:316: in function 'readObject'
	/home/aron/torch/install/share/lua/5.1/torch/File.lua:316: in function 'readObject'
	...
	/home/aron/torch/install/share/lua/5.1/torch/File.lua:300: in function 'readObject'
	/home/aron/torch/install/share/lua/5.1/torch/File.lua:316: in function 'readObject'
	/home/aron/torch/install/share/lua/5.1/nngraph/gmodule.lua:402: in function 'read'
	/home/aron/torch/install/share/lua/5.1/torch/File.lua:298: in function 'readObject'
	/home/aron/torch/install/share/lua/5.1/nn/Module.lua:108: in function 'clone'
	./misc/LanguageModel.lua:51: in function 'createClones'
	eval.lua:96: in main chunk
	[C]: in function 'dofile'
	...aron/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by soumith** [comment]
What is the command that you used for this?

**Comment by aronfothi** [comment]
th eval.lua -model /home/aron/neuraltalk2/Model/model_id1-501-1448236541.t7 -image_folder /home/aron/neuraltalk2/Images -num_images 3

**Comment by aronfothi** [comment]
I tried to debug the issue with LUA Development Tool. When i just run it i get the same error, but when i run it in debug the eval runs slow but without error. In these days the THCStorage was restructured. I am wondering if it could change the behaviour in my configuration

**Comment by barneyElDinosaurio** [comment]
Ive the same error, i tried installing and reintalling but its the ever appear the same, im trying in Ubuntu 14.

**Comment by soumith** [comment]
I've just tested this with the latest torch (installed today). I am seeing no issues. Weird.
I can help debug if any of you give me more information. Your CUDA version, your GPU model etc.

**Comment by aronfothi** [comment]
My config: 
* linux: ubuntu 14.04 64bit
* gpu: gtx950 2GB
* driver: 352.63
* cuda: 7.5-18 (cuda-repo-ubuntu1404-7-5-local_7.5-18_amd64.deb)

I was monitoring the video memory usage and it really reached the100%
I've stopped the x server but it was not enough

**Comment by barneyElDinosaurio** [comment]
I've the same config, just change this :
(--)Gpu|Geforce 720M
(//)Driver|352.68

**Comment by soumith** [comment]
Ok, so maybe you both are running out of memory? 2GB is small. Did either of you ever manage to not run out of memory while running neuraltalk2?

**Comment by aronfothi** [comment]
Yes. On 19th of December I run it without error with the same config.
Could you measure the video memory usage during eval (and train)?

**Comment by soumith** [comment]
yes, you can see nvidia-smi -l

**Comment by aronfothi** [comment]
i know :)
Could you measure it on your PC. I should know what is the required memory if we cannot fix this issue

**Comment by soumith** [comment]
I just checked. It went up till 2.8GB. I can see if we can reduce memory usage somehow.

**Comment by aronfothi** [comment]
it seems it was somehow doubled

**Comment by soumith** [comment]
Oh, did you measure it before? was it around 1.4GB?

**Comment by aronfothi** [comment]
Not really. But i have seen an issue about the 1GB vga is not enough and the free memory is ~1,5GB because the x and compiz

**Comment by dasguptar** [comment]
@soumith I faced this issue as well. It seems to be a memory leak with either `CuDNN` or with some newer changes to the `nn` library. (`THNN` maybe? not sure!)
I'm running on a GTX970 with 4GB memory running CUDA 7.0
Earlier, the pre-trained model would need around 1.7 / 1.8 GB. Memory would shoot up a bit while the clones were being constructed, but then reduce and stabilise below 2GB.
Now, when I reach the `constructing clones inside the LanguageModel` portion, the memory creeps up to 4GB and I get the `out of memory` error.

**Comment by soumith** [comment]
@dasguptar hmm, good to know. I'm looking into it now.

**Comment by soumith** [comment]
@dasguptar could you tell me approximately when is "earlier". 

I've been playing with it for a bit now, and the memory requirements for eval right now seem to be:
- current master: 2.6 GB
- with some quick and simple hacks: 0.8 GB

The way I simulate limited memory is via: https://github.com/soumith/neuraltalk2/blob/f26c88b78a31f649fd9999b4a6f3cc14a6a51fea/eval.lua#L63-L69

I think there is something weird that seems to have been introduced between now and whenever you call "earlier", and given a more narrow time frame, I can investigate. If you dont remember, that's fine, I can do a git bisect. 
Let me know.

**Comment by dasguptar** [comment]
@soumith OK, so I'm not using the eval script as is. I'm only using a part of it, available as a gist [here](https://gist.github.com/dasguptar/2945e47a71fc2f4bc912). Basically I load the pretrained model, unsanitize the gradients and make a forward pass on a batch of images to get the log probabilities, and then sample captions for them. I tried running this on the same machine with a GTX970, 4GB of memory, with 2 separate users and hence 2 separate Torch installations.

Using installation 1, (soumith/distro@9f48e5f1504698015f834809f3eb605198b36561, Oct 12), loading the model takes `1393`MB. Memory consumption shoots up to `2283`MB while constructing the clones, but falls to `1393`MB again. 

Using installation 2, (soumith/distro@8ff677e9731980f5d0323582e0758a2460f0ebc1, Dec 29), loading the model takes a whopping `2594`MB. The cloning fails after that.

The `eval.lua` script runs on both installations, but requires more memory on the 2nd installation. My gist has a `unsanitize_gradients` call, which seems to be causing the out of memory error on the newer installation.

**Comment by fairylrt** [comment]
I'm meeting the same problem. Does anyone find where the problem is?

**Comment by shaayaansayed** [comment]
Having the same issues in clone construction. It was working fine before, but I had to reinstall torch and some other packages (for unrelated issues) and I started getting this out of memory problem now.

**Comment by barneyElDinosaurio** [comment]
[this](https://github.com/soumith/neuraltalk2/blob/f26c88b78a31f649fd9999b4a6f3cc14a6a51fea/eval.lua#L63-L69)

**Comment by ersingencturk** [comment]
same here:

mac osx el capitan
Geforce750m
2gb graphic card ram
CUDA Driver Version: 7.5.22

**Comment by ersingencturk** [comment]
commenting out these part fixes the memory issue

```
function layer:createClones()
  -- construct the net clones
  print('constructing clones inside the LanguageModel')
  self.clones = {self.core}
  self.lookup_tables = {self.lookup_table}
  -- for t=2,self.seq_length+2 do
  --   self.clones[t] = self.core:clone('weight', 'bias', 'gradWeight', 'gradBias')
  --   self.lookup_tables[t] = self.lookup_table:clone('weight', 'gradWeight')
  -- end
end```

**Comment by shaayaansayed** [comment]
@soumith already comments out the cloning but I assume that only works if you are solely doing evaluation. As far as I understand, commenting the cloning is not a viable solution for the training phase or else the gradients across timesteps won't accumulate properly.

**Comment by ersingencturk** [comment]
you might be right, I haven't tried training.
I was trying to use the eval script and it works.

**Comment by soumith** [comment]
@shaayaansayed yes it only works for evaluation....

**Comment by shaayaansayed** [comment]
@soumith were you able to determine what changes between the previous release and now is causing this increase in gpu memory use? I also recorded the same numbers as @dasguptar and the memory has indeed almost doubled while the clones are being created. Whereas before I was able to train my own models with 80 or so clones, I can't finish cloning them anymore. Is this a bug or something we'll have to live with?

**Comment by soumith** [comment]
It's something that I spent a little bit of time investigating, and have to spend a little more time on it, but it will be fixed soon.
@colesbury this is the bug that I was trying to get to the bottom of.

**Comment by eladhoffer** [comment]
You should try adding ``` cutorch.setHeapTracking(true) ```

**Comment by soumith** [comment]
Ok the issue is indeed this https://github.com/torch/cutorch/commit/df463695f0cd387736917e02abaafa63c00bbed3#commitcomment-15478238

It will be patched in a day.
What @eladhoffer said is the solution.

**Comment by soumith** [comment]
These memory issues should be fixed now, if you update cutorch

**Comment by kepricon** [comment]
@soumith Hi
yesterday i installed all the environment including cutorch using luarocks install command.
Unfortunately, I am still have same problem.I used 2GB memory gpu on cuda 7.0 and cudnn 7.0.

Is it not sufficient to train using VGG16 pretrained model?
Or is there any other problem on my environment?

If my gpu memory is not sufficient, I would like to use another pre-trained model such as AlexNet.
Does it make sense?

BTW, Thank you for sharing this great project.

**Comment by ionelhosu** [comment]
I had the same problem on my laptop and updating cutorch fixed it.

**Comment by fairylrt** [comment]
@ionelhosu It does help. Thank you so much.

**Comment by samyk** [comment]
Hello all! I'm also getting this error. I tried updating to latest cutorch by just now running:
```
luarocks install cutorch
luarocks install torch
```

But also getting similar errors:
```
$ th artistic_video.lua 
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Style image size: 348 x 452	
Setting up temporal consistency.	
Setting up style layer  	2	:	relu1_1	
Setting up style layer  	7	:	relu2_1	
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-5997/cutorch/lib/THC/generic/THCStorage.cu line=40 error=2 : out of memory
/usr/local/torch/install/bin/luajit: /usr/local/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 5 module of nn.Sequential:
/usr/local/torch/install/share/lua/5.1/nn/THNN.lua:109: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-5997/cutorch/lib/THC/generic/THCStorage.cu:40
stack traceback:
	[C]: in function 'v'
	/usr/local/torch/install/share/lua/5.1/nn/THNN.lua:109: in function 'SpatialConvolutionMM_updateOutput'
	...al/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:96: in function <...al/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:92>
	[C]: in function 'xpcall'
	/usr/local/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/usr/local/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./artistic_video_core.lua:229: in function 'buildNet'
	artistic_video.lua:107: in function 'main'
	artistic_video.lua:359: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010fa99be0

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/usr/local/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/usr/local/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./artistic_video_core.lua:229: in function 'buildNet'
	artistic_video.lua:107: in function 'main'
	artistic_video.lua:359: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010fa99be0
```

**Comment by shimen** [comment]
same problem here

**Comment by xiahaoyun** [comment]
I have same problem,too.

[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Setting up style layer      2   :   relu1_1 
Setting up style layer      7   :   relu2_1 
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-2187/cutorch/lib/THC/generic/THCStorage.cu line=40 error=2 : out of memory
/home/yun/torch/install/bin/luajit: /home/yun/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 8 module of nn.Sequential:
/home/yun/torch/install/share/lua/5.1/nn/THNN.lua:110: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-2187/cutorch/lib/THC/generic/THCStorage.cu:40
stack traceback:
    [C]: in function 'v'
    /home/yun/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialConvolutionMM_updateOutput'
    ...un/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:96: in function <...un/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:92>
    [C]: in function 'xpcall'
    /home/yun/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /home/yun/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
    neural_style.lua:204: in function 'main'
    neural_style.lua:515: in main chunk
    [C]: in function 'dofile'
    .../yun/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
    [C]: in function 'error'
    /home/yun/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
    /home/yun/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
    neural_style.lua:204: in function 'main'
    neural_style.lua:515: in main chunk
    [C]: in function 'dofile'
    .../yun/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
th neural_style.lua -style_image s2.jpg -content_image c.jpg  4.84s user 1.01s system 102% cpu 5.727 total

**Comment by petronny** [comment]
@xiahaoyun 创建一个500大小的neural_style需要3.6G的显存
默认的image_size=512，你试一试小点的image_size?

**Comment by xiahaoyun** [comment]
小一点的就成功了

**Comment by panfengli** [comment]
`nvidia-smi`
Sometimes a process may occupy too much GPU memory, you can try to kill this process. I have encountered `/usr/lib/xorg/Xorg` occupies around 1800 Mb GPU memory.

**Comment by HiZhaoxiaoyang** [comment]
Smaller output size or switch to CPU mode.

**Comment by loretoparisi** [comment]
I'm getting the same error on `nvidia-docker` https://github.com/facebookresearch/fairseq/issues/31

I have
```
Tue May 16 21:04:21 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   40C    P8    17W / 125W |   3977MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

and I was able to run several times, before getting this error:

```
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-1095/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/torch/File.lua:351: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-1095/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'read'
	/root/torch/install/share/lua/5.1/torch/File.lua:351: in function </root/torch/install/share/lua/5.1/torch/File.lua:245>
	[C]: in function 'read'
	/root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/root/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/root/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	...
	/root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/root/torch/install/share/lua/5.1/torch/File.lua:353: in function 'readObject'
	/root/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	.../install/share/lua/5.1/fairseq/models/ensemble_model.lua:32: in function '__init'
	/root/torch/install/share/lua/5.1/torch/init.lua:91: in function 'new'
	...install/share/lua/5.1/fairseq/scripts/generate-lines.lua:153: in main chunk
	[C]: in function 'require'
	...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
	[C]: at 0x00405d50
```

**Comment by hhung516** [comment]
I ran into this issue training deepmask with Lua 5.2 (instead of default LuaJIT comes within Torch7). Echo what certain posts said above, if I lower the batch size (default 32, I'm using 4), then it seems to be running fine. Still waiting for the training to finish, fingers crossed....

My setup is Ubuntu 16.04.x w GTX 980Ti (6G GPU memory), by monitoring the GPU I see memory usage fluctuates between 20-50%.

**Comment by WillQuCD** [comment]
just use a smaller batch size.

**Comment by tannaz-k** [comment]
Hi
Did anyone find a solution for this issue?!

**Comment by MozhdehDokhani** [comment]
Hi,
Did anyone find a solution for this issue? :(
I've tried smaller batch size too (even batch size 1). didn't work.

P.S when I run it on CPU mode by passing the parameter -gpuid -1, it starts training. But I think it never ends!
